Feature/syslogng support
banzaicloud/logging-operator pull request #1053
Opened 2022-07-19 08:35 UTC by tarokkk

| Q               | A
| --------------- | ---
| Bug fix?        | no/yes
| New feature?    | no/yes
| API breaks?     | no/yes
| Deprecations?   | no/yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### What's in this PR?

### Why?

### Additional context

### Checklist

- [ ] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

2022-11-17 17:02 UTC, bshifter approved these changes

2022-11-20 09:04 UTC, siliconbrain requested changes
@bshifter some of your private data has leak into the commits. I tried to mark all of them, but I might have missed some. Also, there is the `kubebuilder` binary, which I couldn't mark on this wonderful Github UI.

2022-11-20 09:04 UTC, siliconbrain commented on patch.diff
> + imagePullSecrets: []
data leak
```suggestion
```

2022-11-21 14:19 UTC, siliconbrain approved these changes

2022-12-21 07:48 UTC, ahma approved these changes

2022-12-21 08:07 UTC, siliconbrain approved these changes

2022-12-21 08:19 UTC, merged