fluentbit: Add support for Kube_Meta_Cache_TTL parameter
banzaicloud/logging-operator pull request #1144
Opened 2022-12-01 16:44 UTC by Jellyfrog

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | 
| License         | Apache 2.0

### What's in this PR?

Adding support for another parameter from https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#configuration-parameters

### Why?

Currently it caches the metadata forever, so when changing a pods label it wont be reflected in the log output until fluentbit is restarted.

### Additional context

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### To Do

2022-12-01 16:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/banzaicloud/logging-operator?pullRequest=1144) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/banzaicloud/logging-operator?pullRequest=1144) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/banzaicloud/logging-operator?pullRequest=1144) it.</sub>

2022-12-01 17:12 UTC, aslafy-z submitted a review, later dismissed

2022-12-05 07:33 UTC, ahma requested changes
@Jellyfrog could you please run a ` make manifests`  here ?

2022-12-05 10:15 UTC, Jellyfrog commented
@ahma fixed, please note I didnt have a chance to actually test this, I copied how the other options are exposed, and hope for the best :)

2022-12-05 16:22 UTC, ahma approved these changes

2022-12-05 16:22 UTC, merged