Custom cached watchers
banzaicloud/logging-operator pull request #758
Opened 2021-06-18 14:29 UTC by bshifter

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    |yes
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
Custom-filtered client cache for watchers. 

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

2021-06-18 14:32 UTC, siliconbrain approved these changes
lgtm

2021-06-18 15:09 UTC, pepov requested changes

2021-06-18 15:09 UTC, pepov commented on main.go
> +	flag.StringVar(&loggingRef, "logging-name", "", "logging-operator name reference")
```suggestion
	flag.StringVar(&loggingRef, "watch-logging-name", "", "logging resource name to optionally filter the list of watched objects based on which logging they belong to by checking the app.kubernetes.io/managed-by label")
```

2021-06-18 15:09 UTC, pepov commented on main.go
> +	flag.StringVar(&namespace, "logging-namespace", "", "logging-operator namespace")
```suggestion
	flag.StringVar(&namespace, "watch-namespace", "", "namespace to filter the list of watched objects")
```

2021-06-21 11:22 UTC, pepov approved these changes

2021-06-21 12:19 UTC, merged